/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ArcAnnotation } from './arcAnnotation';

export interface Arc {
  annotation: ArcAnnotation;
  source: string;
  target: string;
  variable?: boolean;
}
