/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface BodyImportOcel {
  /** An OCEL 2.0 event log (.sqlite format) */
  file: Blob;
}
