/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DateDistributionItemEntityCount } from './dateDistributionItemEntityCount';

export interface DateDistributionItem {
  date: string;
  entity_count: DateDistributionItemEntityCount;
}
