/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type E2OCountFilterConfigDirection = typeof E2OCountFilterConfigDirection[keyof typeof E2OCountFilterConfigDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const E2OCountFilterConfigDirection = {
  source: 'source',
  target: 'target',
} as const;
