/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type E2oParams = {
direction?: 'source' | 'target' | null;
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
