/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EdgeAnnotation } from './edgeAnnotation';

export interface Edge {
  annotation: EdgeAnnotation;
  source: string;
  target: string;
  object_type: string;
}
