/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DateDistributionItem } from './dateDistributionItem';

export interface EntityTimeInfo {
  start_time: string;
  end_time: string;
  date_distribution: DateDistributionItem[];
}
