/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ImportOcelParams = {
/**
 * The name of the uploaded file
 * @pattern [\w\-\(\)]+\.[a-z]+
 */
name: string;
};
