/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectAttributes200Item } from './objectAttributes200Item';

export type ObjectAttributes200 = {[key: string]: ObjectAttributes200Item[]};
