/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectCentricPetriNetAnnotation } from './objectCentricPetriNetAnnotation';
import type { Place } from './place';
import type { Transition } from './transition';
import type { Arc } from './arc';

export interface ObjectCentricPetriNet {
  annotation: ObjectCentricPetriNetAnnotation;
  places: Place[];
  transitions: Transition[];
  arcs: Arc[];
  type: 'ocpn';
}
