/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface OcelMetadata {
  id: string;
  name: string;
  created_at: string;
  extensions: string[];
}
