/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type OcelotPaginatedEventsParams = {
/**
 * Activity name
 */
activity: string;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
sort_by?: string | null;
ascending?: boolean;
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
