/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcelListResponseCurrentOcelId } from './ocelListResponseCurrentOcelId';
import type { OcelMetadata } from './ocelMetadata';
import type { UploadingOcelMetadata } from './uploadingOcelMetadata';

export interface OcelListResponse {
  current_ocel_id: OcelListResponseCurrentOcelId;
  ocels: OcelMetadata[];
  uploading_ocels: UploadingOcelMetadata[];
}
