/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PlaceAnnotation } from './placeAnnotation';
import type { PlacePlaceType } from './placePlaceType';

export interface Place {
  annotation: PlaceAnnotation;
  id: string;
  object_type: string;
  place_type: PlacePlaceType;
}
