/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface RelationCountSummary {
  qualifier: string;
  source: string;
  target: string;
  min_count: number;
  max_count: number;
  sum: number;
}
