/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectCentricDirectlyFollowsGraph } from './objectCentricDirectlyFollowsGraph';
import type { ObjectCentricPetriNet } from './objectCentricPetriNet';
import type { Totem } from './totem';

export type ResourceInputEntity = ObjectCentricDirectlyFollowsGraph | ObjectCentricPetriNet | Totem;
