/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ResourceInputMetaData } from './resourceInputMetaData';
import type { ResourceInputEntity } from './resourceInputEntity';

export interface ResourceInput {
  id: string;
  name: string;
  created_at: string;
  source: string;
  meta_data: ResourceInputMetaData;
  entity: ResourceInputEntity;
}
