/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskSummaryMetadata } from './taskSummaryMetadata';

export interface TaskSummary {
  key: string;
  name: string;
  state: TaskState;
  has_result: boolean;
  metadata: TaskSummaryMetadata;
}
