/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TotemEdgeAnnotationAnyOf } from './totemEdgeAnnotationAnyOf';

export type TotemEdgeAnnotation = TotemEdgeAnnotationAnyOf | null;
