/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TotemEdgeLc = typeof TotemEdgeLc[keyof typeof TotemEdgeLc];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TotemEdgeLc = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  '01': '0...1',
  '1*': '1..*',
  '0*': '0...*',
} as const;
