/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TotemAnnotation } from './totemAnnotation';
import type { TotemEdge } from './totemEdge';

export interface Totem {
  annotation: TotemAnnotation;
  object_types: string[];
  edges: TotemEdge[];
  type: 'totem';
}
