/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TotemEdgeTr = typeof TotemEdgeTr[keyof typeof TotemEdgeTr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TotemEdgeTr = {
  D: 'D',
  Di: 'Di',
  I: 'I',
  Ii: 'Ii',
  P: 'P',
} as const;
