/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TransitionAnnotation } from './transitionAnnotation';
import type { TransitionLabel } from './transitionLabel';

export interface Transition {
  annotation: TransitionAnnotation;
  id: string;
  label: TransitionLabel;
}
