version: "3.9"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile  
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
