// This file is auto-generated by scripts/genResourceDefinitionMap.ts
/* eslint-disable */

import ocdfg from "@/resources/ocdfg";
import ocpn from "@/resources/ocpn";
import totem from "@/resources/totem";
import { ResourceType, ResourceViewDefinition } from "@/types/resources";

const defs = [ocdfg, ocpn, totem] as const;

export const resourceDefinitionMap: Partial<{
  [K in ResourceType]: ResourceViewDefinition<K>;
}> = Object.fromEntries(defs.map((def) => [def.type, def]));
