/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  OcdfgParams,
  PetriNetParams,
  Resource,
  SaveOcdfgParams,
  SavePnetParams,
  TaskResponseObjectCentricDirectlyFollowsGraph,
  TaskResponseObjectCentricPetriNet
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Petri Net
 */
export const getPetriNetUrl = (params?: PetriNetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/berti/petriNet?${stringifiedParams}` : `http://localhost:8000/berti/petriNet`
}

export const petriNet = async (params?: PetriNetParams, options?: RequestInit): Promise<TaskResponseObjectCentricPetriNet> => {
  
  return customFetch<TaskResponseObjectCentricPetriNet>(getPetriNetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getPetriNetQueryKey = (params?: PetriNetParams,) => {
    return [`http://localhost:8000/berti/petriNet`, ...(params ? [params]: [])] as const;
    }

    
export const getPetriNetQueryOptions = <TData = Awaited<ReturnType<typeof petriNet>>, TError = HTTPValidationError>(params?: PetriNetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPetriNetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof petriNet>>> = ({ signal }) => petriNet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PetriNetQueryResult = NonNullable<Awaited<ReturnType<typeof petriNet>>>
export type PetriNetQueryError = HTTPValidationError


export function usePetriNet<TData = Awaited<ReturnType<typeof petriNet>>, TError = HTTPValidationError>(
 params: undefined |  PetriNetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof petriNet>>,
          TError,
          Awaited<ReturnType<typeof petriNet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePetriNet<TData = Awaited<ReturnType<typeof petriNet>>, TError = HTTPValidationError>(
 params?: PetriNetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof petriNet>>,
          TError,
          Awaited<ReturnType<typeof petriNet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePetriNet<TData = Awaited<ReturnType<typeof petriNet>>, TError = HTTPValidationError>(
 params?: PetriNetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Petri Net
 */

export function usePetriNet<TData = Awaited<ReturnType<typeof petriNet>>, TError = HTTPValidationError>(
 params?: PetriNetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof petriNet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPetriNetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Ocdfg
 */
export const getOcdfgUrl = (params?: OcdfgParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/berti/ocdfg?${stringifiedParams}` : `http://localhost:8000/berti/ocdfg`
}

export const ocdfg = async (params?: OcdfgParams, options?: RequestInit): Promise<TaskResponseObjectCentricDirectlyFollowsGraph> => {
  
  return customFetch<TaskResponseObjectCentricDirectlyFollowsGraph>(getOcdfgUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getOcdfgQueryKey = (params?: OcdfgParams,) => {
    return [`http://localhost:8000/berti/ocdfg`, ...(params ? [params]: [])] as const;
    }

    
export const getOcdfgQueryOptions = <TData = Awaited<ReturnType<typeof ocdfg>>, TError = HTTPValidationError>(params?: OcdfgParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOcdfgQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ocdfg>>> = ({ signal }) => ocdfg(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OcdfgQueryResult = NonNullable<Awaited<ReturnType<typeof ocdfg>>>
export type OcdfgQueryError = HTTPValidationError


export function useOcdfg<TData = Awaited<ReturnType<typeof ocdfg>>, TError = HTTPValidationError>(
 params: undefined |  OcdfgParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocdfg>>,
          TError,
          Awaited<ReturnType<typeof ocdfg>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcdfg<TData = Awaited<ReturnType<typeof ocdfg>>, TError = HTTPValidationError>(
 params?: OcdfgParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocdfg>>,
          TError,
          Awaited<ReturnType<typeof ocdfg>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcdfg<TData = Awaited<ReturnType<typeof ocdfg>>, TError = HTTPValidationError>(
 params?: OcdfgParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Ocdfg
 */

export function useOcdfg<TData = Awaited<ReturnType<typeof ocdfg>>, TError = HTTPValidationError>(
 params?: OcdfgParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocdfg>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOcdfgQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Save Ocdfg
 */
export const getSaveOcdfgUrl = (params?: SaveOcdfgParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/berti/ocdfg?${stringifiedParams}` : `http://localhost:8000/berti/ocdfg`
}

export const saveOcdfg = async (params?: SaveOcdfgParams, options?: RequestInit): Promise<Resource> => {
  
  return customFetch<Resource>(getSaveOcdfgUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSaveOcdfgMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOcdfg>>, TError,{params?: SaveOcdfgParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof saveOcdfg>>, TError,{params?: SaveOcdfgParams}, TContext> => {

const mutationKey = ['saveOcdfg'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveOcdfg>>, {params?: SaveOcdfgParams}> = (props) => {
          const {params} = props ?? {};

          return  saveOcdfg(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SaveOcdfgMutationResult = NonNullable<Awaited<ReturnType<typeof saveOcdfg>>>
    
    export type SaveOcdfgMutationError = HTTPValidationError

    /**
 * @summary Save Ocdfg
 */
export const useSaveOcdfg = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOcdfg>>, TError,{params?: SaveOcdfgParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveOcdfg>>,
        TError,
        {params?: SaveOcdfgParams},
        TContext
      > => {

      const mutationOptions = getSaveOcdfgMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Save Pnet
 */
export const getSavePnetUrl = (params?: SavePnetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/berti/pnet?${stringifiedParams}` : `http://localhost:8000/berti/pnet`
}

export const savePnet = async (params?: SavePnetParams, options?: RequestInit): Promise<Resource> => {
  
  return customFetch<Resource>(getSavePnetUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSavePnetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof savePnet>>, TError,{params?: SavePnetParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof savePnet>>, TError,{params?: SavePnetParams}, TContext> => {

const mutationKey = ['savePnet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof savePnet>>, {params?: SavePnetParams}> = (props) => {
          const {params} = props ?? {};

          return  savePnet(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SavePnetMutationResult = NonNullable<Awaited<ReturnType<typeof savePnet>>>
    
    export type SavePnetMutationError = HTTPValidationError

    /**
 * @summary Save Pnet
 */
export const useSavePnet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof savePnet>>, TError,{params?: SavePnetParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof savePnet>>,
        TError,
        {params?: SavePnetParams},
        TContext
      > => {

      const mutationOptions = getSavePnetMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    