/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  HTTPValidationError,
  ImportDefaultParams,
  OcelResponse
} from '.././';





/**
 * @summary Import default OCEL
 */
export const importDefault = (
    params: ImportDefaultParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OcelResponse>> => {
    
    
    return axios.get(
      `/import-default`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getImportDefaultQueryKey = (params: ImportDefaultParams,) => {
    return [`/import-default`, ...(params ? [params]: [])] as const;
    }

    
export const getImportDefaultQueryOptions = <TData = Awaited<ReturnType<typeof importDefault>>, TError = AxiosError<HTTPValidationError>>(params: ImportDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getImportDefaultQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof importDefault>>> = ({ signal }) => importDefault(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ImportDefaultQueryResult = NonNullable<Awaited<ReturnType<typeof importDefault>>>
export type ImportDefaultQueryError = AxiosError<HTTPValidationError>


export function useImportDefault<TData = Awaited<ReturnType<typeof importDefault>>, TError = AxiosError<HTTPValidationError>>(
 params: ImportDefaultParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof importDefault>>,
          TError,
          Awaited<ReturnType<typeof importDefault>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useImportDefault<TData = Awaited<ReturnType<typeof importDefault>>, TError = AxiosError<HTTPValidationError>>(
 params: ImportDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof importDefault>>,
          TError,
          Awaited<ReturnType<typeof importDefault>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useImportDefault<TData = Awaited<ReturnType<typeof importDefault>>, TError = AxiosError<HTTPValidationError>>(
 params: ImportDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Import default OCEL
 */

export function useImportDefault<TData = Awaited<ReturnType<typeof importDefault>>, TError = AxiosError<HTTPValidationError>>(
 params: ImportDefaultParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof importDefault>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getImportDefaultQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



