/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FilterPipeLine,
  GetFiltersParams,
  HTTPValidationError,
  SetFiltersParams
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Filter
 */
export const getGetFiltersUrl = (params?: GetFiltersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/filter/?${stringifiedParams}` : `http://localhost:8000/filter/`
}

export const getFilters = async (params?: GetFiltersParams, options?: RequestInit): Promise<FilterPipeLine> => {
  
  return customFetch<FilterPipeLine>(getGetFiltersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetFiltersQueryKey = (params?: GetFiltersParams,) => {
    return [`http://localhost:8000/filter/`, ...(params ? [params]: [])] as const;
    }

    
export const getGetFiltersQueryOptions = <TData = Awaited<ReturnType<typeof getFilters>>, TError = HTTPValidationError>(params?: GetFiltersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFiltersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilters>>> = ({ signal }) => getFilters(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFiltersQueryResult = NonNullable<Awaited<ReturnType<typeof getFilters>>>
export type GetFiltersQueryError = HTTPValidationError


export function useGetFilters<TData = Awaited<ReturnType<typeof getFilters>>, TError = HTTPValidationError>(
 params: undefined |  GetFiltersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilters>>,
          TError,
          Awaited<ReturnType<typeof getFilters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilters<TData = Awaited<ReturnType<typeof getFilters>>, TError = HTTPValidationError>(
 params?: GetFiltersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilters>>,
          TError,
          Awaited<ReturnType<typeof getFilters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilters<TData = Awaited<ReturnType<typeof getFilters>>, TError = HTTPValidationError>(
 params?: GetFiltersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Filter
 */

export function useGetFilters<TData = Awaited<ReturnType<typeof getFilters>>, TError = HTTPValidationError>(
 params?: GetFiltersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilters>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFiltersQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Set Filter
 */
export const getSetFiltersUrl = (params?: SetFiltersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/filter/?${stringifiedParams}` : `http://localhost:8000/filter/`
}

export const setFilters = async (filterPipeLine: FilterPipeLine,
    params?: SetFiltersParams, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getSetFiltersUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      filterPipeLine,)
  }
);}




export const getSetFiltersMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setFilters>>, TError,{data: FilterPipeLine;params?: SetFiltersParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setFilters>>, TError,{data: FilterPipeLine;params?: SetFiltersParams}, TContext> => {

const mutationKey = ['setFilters'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setFilters>>, {data: FilterPipeLine;params?: SetFiltersParams}> = (props) => {
          const {data,params} = props ?? {};

          return  setFilters(data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SetFiltersMutationResult = NonNullable<Awaited<ReturnType<typeof setFilters>>>
    export type SetFiltersMutationBody = FilterPipeLine
    export type SetFiltersMutationError = HTTPValidationError

    /**
 * @summary Set Filter
 */
export const useSetFilters = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setFilters>>, TError,{data: FilterPipeLine;params?: SetFiltersParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setFilters>>,
        TError,
        {data: FilterPipeLine;params?: SetFiltersParams},
        TContext
      > => {

      const mutationOptions = getSetFiltersMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    