/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ResourceInput,
  ResourceOutput,
  UpdateResourceParams
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Returns all available resources
 */
export const getGetResourcesUrl = () => {


  

  return `http://localhost:8000/resources/`
}

export const getResources = async ( options?: RequestInit): Promise<ResourceOutput[]> => {
  
  return customFetch<ResourceOutput[]>(getGetResourcesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetResourcesQueryKey = () => {
    return [`http://localhost:8000/resources/`] as const;
    }

    
export const getGetResourcesQueryOptions = <TData = Awaited<ReturnType<typeof getResources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResourcesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResources>>> = ({ signal }) => getResources({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof getResources>>>
export type GetResourcesQueryError = unknown


export function useGetResources<TData = Awaited<ReturnType<typeof getResources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResources>>,
          TError,
          Awaited<ReturnType<typeof getResources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResources<TData = Awaited<ReturnType<typeof getResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResources>>,
          TError,
          Awaited<ReturnType<typeof getResources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResources<TData = Awaited<ReturnType<typeof getResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all available resources
 */

export function useGetResources<TData = Awaited<ReturnType<typeof getResources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResourcesQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adds a resource to the session
 */
export const getAddResourceUrl = () => {


  

  return `http://localhost:8000/resources/`
}

export const addResource = async (resourceInput: ResourceInput, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getAddResourceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resourceInput,)
  }
);}




export const getAddResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{data: ResourceInput}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{data: ResourceInput}, TContext> => {

const mutationKey = ['addResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addResource>>, {data: ResourceInput}> = (props) => {
          const {data} = props ?? {};

          return  addResource(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddResourceMutationResult = NonNullable<Awaited<ReturnType<typeof addResource>>>
    export type AddResourceMutationBody = ResourceInput
    export type AddResourceMutationError = HTTPValidationError

    /**
 * @summary Adds a resource to the session
 */
export const useAddResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addResource>>, TError,{data: ResourceInput}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addResource>>,
        TError,
        {data: ResourceInput},
        TContext
      > => {

      const mutationOptions = getAddResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Resource
 */
export const getGetResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}`
}

export const getResource = async (resourceId: string, options?: RequestInit): Promise<ResourceOutput> => {
  
  return customFetch<ResourceOutput>(getGetResourceUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetResourceQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/${resourceId}`] as const;
    }

    
export const getGetResourceQueryOptions = <TData = Awaited<ReturnType<typeof getResource>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResourceQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResource>>> = ({ signal }) => getResource(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResourceQueryResult = NonNullable<Awaited<ReturnType<typeof getResource>>>
export type GetResourceQueryError = HTTPValidationError


export function useGetResource<TData = Awaited<ReturnType<typeof getResource>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResource>>,
          TError,
          Awaited<ReturnType<typeof getResource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResource<TData = Awaited<ReturnType<typeof getResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResource>>,
          TError,
          Awaited<ReturnType<typeof getResource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResource<TData = Awaited<ReturnType<typeof getResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Resource
 */

export function useGetResource<TData = Awaited<ReturnType<typeof getResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResourceQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update Resource
 */
export const getUpdateResourceUrl = (resourceId: string,
    params: UpdateResourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/resources/${resourceId}?${stringifiedParams}` : `http://localhost:8000/resources/${resourceId}`
}

export const updateResource = async (resourceId: string,
    params: UpdateResourceParams, options?: RequestInit): Promise<ResourceOutput> => {
  
  return customFetch<ResourceOutput>(getUpdateResourceUrl(resourceId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getUpdateResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;params: UpdateResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;params: UpdateResourceParams}, TContext> => {

const mutationKey = ['updateResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateResource>>, {resourceId: string;params: UpdateResourceParams}> = (props) => {
          const {resourceId,params} = props ?? {};

          return  updateResource(resourceId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateResource>>>
    
    export type UpdateResourceMutationError = HTTPValidationError

    /**
 * @summary Update Resource
 */
export const useUpdateResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;params: UpdateResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateResource>>,
        TError,
        {resourceId: string;params: UpdateResourceParams},
        TContext
      > => {

      const mutationOptions = getUpdateResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Delete Resource
 */
export const getDeleteResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}`
}

export const deleteResource = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDeleteResourceUrl(resourceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['deleteResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteResource>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  deleteResource(resourceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteResource>>>
    
    export type DeleteResourceMutationError = HTTPValidationError

    /**
 * @summary Delete Resource
 */
export const useDeleteResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteResource>>,
        TError,
        {resourceId: string},
        TContext
      > => {

      const mutationOptions = getDeleteResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Download Resource
 */
export const getDownloadResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}/download`
}

export const downloadResource = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDownloadResourceUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getDownloadResourceQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/${resourceId}/download`] as const;
    }

    
export const getDownloadResourceQueryOptions = <TData = Awaited<ReturnType<typeof downloadResource>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadResourceQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadResource>>> = ({ signal }) => downloadResource(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadResourceQueryResult = NonNullable<Awaited<ReturnType<typeof downloadResource>>>
export type DownloadResourceQueryError = HTTPValidationError


export function useDownloadResource<TData = Awaited<ReturnType<typeof downloadResource>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadResource>>,
          TError,
          Awaited<ReturnType<typeof downloadResource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadResource<TData = Awaited<ReturnType<typeof downloadResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadResource>>,
          TError,
          Awaited<ReturnType<typeof downloadResource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadResource<TData = Awaited<ReturnType<typeof downloadResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Resource
 */

export function useDownloadResource<TData = Awaited<ReturnType<typeof downloadResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadResource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadResourceQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



