# AUTO-GENERATED by gen_union_into_init.py — do not edit manually

from .ocdfg import ObjectCentricDirectlyFollowsGraph
from .ocpn import ObjectCentricPetriNet
from .totem import Totem

from typing import Annotated, Any, Union
from pydantic import Field
from pydantic.main import BaseModel

__all__ = ["ObjectCentricDirectlyFollowsGraph", "ObjectCentricPetriNet", "Totem", "ResourceUnion"]

ResourceUnion = Annotated[
    Union[ObjectCentricDirectlyFollowsGraph, ObjectCentricPetriNet, Totem],
    Field(discriminator="type")
]

class Resource(BaseModel):
    id: str
    name: str
    created_at: str
    source: str
    meta_data: dict[str, Any]
    entity: ResourceUnion
