# AUTO-GENERATED by gen_union_into_init.py — do not edit manually

from .ocdfg import ObjectCentricDirectlyFollowsGraph
from .ocpn import ObjectCentricPetriNet


from typing import Annotated, Union
from pydantic import Field

__all__ = [
    "ObjectCentricDirectlyFollowsGraph",
    "ObjectCentricPetriNet",
    "ResourceUnion",
]

ResourceUnion = Annotated[
    Union[ObjectCentricDirectlyFollowsGraph, ObjectCentricPetriNet],
    Field(discriminator="type"),
]
