/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ResourceOutput,
  TaskResponseTotem,
  TotemSaveTotemParams,
  TotemTotemParams
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Totem
 */
export const getTotemTotemUrl = (params?: TotemTotemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/totem/totem?${stringifiedParams}` : `http://localhost:8000/totem/totem`
}

export const totemTotem = async (params?: TotemTotemParams, options?: RequestInit): Promise<TaskResponseTotem> => {
  
  return customFetch<TaskResponseTotem>(getTotemTotemUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getTotemTotemQueryKey = (params?: TotemTotemParams,) => {
    return [`http://localhost:8000/totem/totem`, ...(params ? [params]: [])] as const;
    }

    
export const getTotemTotemQueryOptions = <TData = Awaited<ReturnType<typeof totemTotem>>, TError = HTTPValidationError>(params?: TotemTotemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTotemTotemQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof totemTotem>>> = ({ signal }) => totemTotem(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TotemTotemQueryResult = NonNullable<Awaited<ReturnType<typeof totemTotem>>>
export type TotemTotemQueryError = HTTPValidationError


export function useTotemTotem<TData = Awaited<ReturnType<typeof totemTotem>>, TError = HTTPValidationError>(
 params: undefined |  TotemTotemParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof totemTotem>>,
          TError,
          Awaited<ReturnType<typeof totemTotem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTotemTotem<TData = Awaited<ReturnType<typeof totemTotem>>, TError = HTTPValidationError>(
 params?: TotemTotemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof totemTotem>>,
          TError,
          Awaited<ReturnType<typeof totemTotem>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTotemTotem<TData = Awaited<ReturnType<typeof totemTotem>>, TError = HTTPValidationError>(
 params?: TotemTotemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Totem
 */

export function useTotemTotem<TData = Awaited<ReturnType<typeof totemTotem>>, TError = HTTPValidationError>(
 params?: TotemTotemParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof totemTotem>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTotemTotemQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Save Pnet
 */
export const getTotemSaveTotemUrl = (params?: TotemSaveTotemParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/totem/totem?${stringifiedParams}` : `http://localhost:8000/totem/totem`
}

export const totemSaveTotem = async (params?: TotemSaveTotemParams, options?: RequestInit): Promise<ResourceOutput> => {
  
  return customFetch<ResourceOutput>(getTotemSaveTotemUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getTotemSaveTotemMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totemSaveTotem>>, TError,{params?: TotemSaveTotemParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof totemSaveTotem>>, TError,{params?: TotemSaveTotemParams}, TContext> => {

const mutationKey = ['totemSaveTotem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof totemSaveTotem>>, {params?: TotemSaveTotemParams}> = (props) => {
          const {params} = props ?? {};

          return  totemSaveTotem(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TotemSaveTotemMutationResult = NonNullable<Awaited<ReturnType<typeof totemSaveTotem>>>
    
    export type TotemSaveTotemMutationError = HTTPValidationError

    /**
 * @summary Save Pnet
 */
export const useTotemSaveTotem = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof totemSaveTotem>>, TError,{params?: TotemSaveTotemParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof totemSaveTotem>>,
        TError,
        {params?: TotemSaveTotemParams},
        TContext
      > => {

      const mutationOptions = getTotemSaveTotemMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    