/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { AttributeFilterConfigMode } from './attributeFilterConfigMode';
import type { AttributeFilterConfigEntityType } from './attributeFilterConfigEntityType';
import type { AttributeFilterConfigMin } from './attributeFilterConfigMin';
import type { AttributeFilterConfigMax } from './attributeFilterConfigMax';
import type { AttributeFilterConfigValues } from './attributeFilterConfigValues';
import type { AttributeFilterConfigRegex } from './attributeFilterConfigRegex';

export interface AttributeFilterConfig {
  mode?: AttributeFilterConfigMode;
  type: 'attribute';
  entity_type: AttributeFilterConfigEntityType;
  target_type: string;
  attribute: string;
  min?: AttributeFilterConfigMin;
  max?: AttributeFilterConfigMax;
  values?: AttributeFilterConfigValues;
  regex?: AttributeFilterConfigRegex;
}
