/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type AttributeFilterConfigTargetType = typeof AttributeFilterConfigTargetType[keyof typeof AttributeFilterConfigTargetType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttributeFilterConfigTargetType = {
  event: 'event',
  object: 'object',
} as const;
