/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type AttributeFilterConfigTarget = typeof AttributeFilterConfigTarget[keyof typeof AttributeFilterConfigTarget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttributeFilterConfigTarget = {
  event: 'event',
  object: 'object',
} as const;
