/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { BaseResponseMsg } from './baseResponseMsg';

export interface BaseResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: BaseResponseMsg;
}
