/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type BertiSavePnetParams = {
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
