/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { BodyRunPluginInput } from './bodyRunPluginInput';
import type { BodyRunPluginInputOcels } from './bodyRunPluginInputOcels';

export interface BodyRunPlugin {
  input: BodyRunPluginInput;
  input_ocels: BodyRunPluginInputOcels;
}
