/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { BodyRunPluginInputOcels } from './bodyRunPluginInputOcels';
import type { BodyRunPluginInput } from './bodyRunPluginInput';

export interface BodyRunPlugin {
  input_ocels: BodyRunPluginInputOcels;
  input?: BodyRunPluginInput;
}
