/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface BooleanAttribute {
  attribute: string;
  type: 'boolean';
  true_count: number;
  false_count: number;
}
