/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { CytoscapeGraphElementsItem } from './cytoscapeGraphElementsItem';
import type { CytoscapeGraphStylesItem } from './cytoscapeGraphStylesItem';

export interface CytoscapeGraph {
  type: 'cytoscape';
  elements: CytoscapeGraphElementsItem[];
  styles: CytoscapeGraphStylesItem[];
}
