/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface DateAttribute {
  attribute: string;
  type: 'date';
  min: string;
  max: string;
}
