/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DefaultOCELUrl } from './defaultOCELUrl';

/**
 * Definition of a default OCEL on the server, for quick access. Supports pre-loading the OCEL on backend init.
 */
export interface DefaultOCEL {
  key: string;
  name: string;
  version: string;
  file: string;
  url?: DefaultOCELUrl;
  preload?: boolean;
  hide?: boolean;
}
