/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type E2OCountFilterConfigType = typeof E2OCountFilterConfigType[keyof typeof E2OCountFilterConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const E2OCountFilterConfigType = {
  e2o_count: 'e2o_count',
} as const;
