/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface EnumInput {
  name: string;
  description?: string;
  default?: unknown;
  type: 'enum';
  options: string[];
}
