/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterConfigTimeRange } from './eventAttributeFilterConfigTimeRange';
import type { EventAttributeFilterConfigNumberRange } from './eventAttributeFilterConfigNumberRange';
import type { EventAttributeFilterConfigValues } from './eventAttributeFilterConfigValues';
import type { EventAttributeFilterConfigRegex } from './eventAttributeFilterConfigRegex';
import type { EventAttributeFilterConfigMode } from './eventAttributeFilterConfigMode';

export interface EventAttributeFilterConfig {
  target_type: string;
  attribute: string;
  time_range?: EventAttributeFilterConfigTimeRange;
  number_range?: EventAttributeFilterConfigNumberRange;
  values?: EventAttributeFilterConfigValues;
  regex?: EventAttributeFilterConfigRegex;
  mode?: EventAttributeFilterConfigMode;
  type: 'event_attribute';
}
