/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventTypeFilterConfigMode } from './eventTypeFilterConfigMode';

export interface EventTypeFilterConfig {
  mode?: EventTypeFilterConfigMode;
  type: 'event_type';
  event_types: string[];
}
