/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventFrequencyFilterConfigMode } from './eventFrequencyFilterConfigMode';

export interface EventFrequencyFilterConfig {
  mode?: EventFrequencyFilterConfigMode;
  type: 'event_frequency';
  frequency: number;
}
