/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type EventTypeFilterConfigType = typeof EventTypeFilterConfigType[keyof typeof EventTypeFilterConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventTypeFilterConfigType = {
  event_type: 'event_type',
} as const;
