/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterConfigMode } from './eventAttributeFilterConfigMode';
import type { EventAttributeFilterConfigMin } from './eventAttributeFilterConfigMin';
import type { EventAttributeFilterConfigMax } from './eventAttributeFilterConfigMax';
import type { EventAttributeFilterConfigValues } from './eventAttributeFilterConfigValues';
import type { EventAttributeFilterConfigRegex } from './eventAttributeFilterConfigRegex';

export interface EventAttributeFilterConfig {
  mode?: EventAttributeFilterConfigMode;
  type: 'event_attribute';
  target_type: string;
  attribute: string;
  min?: EventAttributeFilterConfigMin;
  max?: EventAttributeFilterConfigMax;
  values?: EventAttributeFilterConfigValues;
  regex?: EventAttributeFilterConfigRegex;
}
