/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterConfigTimeRangeAnyOfItem0 } from './eventAttributeFilterConfigTimeRangeAnyOfItem0';
import type { EventAttributeFilterConfigTimeRangeAnyOfItem1 } from './eventAttributeFilterConfigTimeRangeAnyOfItem1';

export type EventAttributeFilterConfigTimeRange = [EventAttributeFilterConfigTimeRangeAnyOfItem0, EventAttributeFilterConfigTimeRangeAnyOfItem1] | null;
