/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterConfigNumberRangeAnyOfItem0 } from "./eventAttributeFilterConfigNumberRangeAnyOfItem0";
import type { EventAttributeFilterConfigNumberRangeAnyOfItem1 } from "./eventAttributeFilterConfigNumberRangeAnyOfItem1";

export type EventAttributeFilterConfigNumberRange =
  | [
      EventAttributeFilterConfigNumberRangeAnyOfItem0,
      EventAttributeFilterConfigNumberRangeAnyOfItem1,
    ]
  | null;
