/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { NumericalAttribute } from './numericalAttribute';
import type { NominalAttribute } from './nominalAttribute';

export type EventAttributes200Item = NumericalAttribute | NominalAttribute;
