/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TimeFrameFilterConfig } from "./timeFrameFilterConfig";
import type { EventAttributeFilterConfig } from "./eventAttributeFilterConfig";
import type { ObjectAttributeFilterConfig } from "./objectAttributeFilterConfig";
import type { ObjectTypeFilterConfig } from "./objectTypeFilterConfig";
import type { EventTypeFilterConfig } from "./eventTypeFilterConfig";
import type { E2OCountFilterConfig } from "./e2OCountFilterConfig";
import type { O2OCountFilterConfig } from "./o2OCountFilterConfig";

export type FilterPipeLinePipelineItem =
  | TimeFrameFilterConfig
  | EventAttributeFilterConfig
  | ObjectAttributeFilterConfig
  | ObjectTypeFilterConfig
  | EventTypeFilterConfig
  | E2OCountFilterConfig
  | O2OCountFilterConfig;
