/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TimeFrameFilterConfig } from './timeFrameFilterConfig';
import type { O2OCountFilterConfig } from './o2OCountFilterConfig';
import type { E2OCountFilterConfig } from './e2OCountFilterConfig';
import type { ObjectTypeFilterConfig } from './objectTypeFilterConfig';
import type { EventTypeFilterConfig } from './eventTypeFilterConfig';

export type FilterPipeLinePipelineItem = TimeFrameFilterConfig | O2OCountFilterConfig | E2OCountFilterConfig | ObjectTypeFilterConfig | EventTypeFilterConfig;
