/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type GetDefaultOcelParams = {
only_latest_versions?: boolean;
only_preloaded?: boolean;
};
