/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { GetOcelResponseCurrentOcelId } from './getOcelResponseCurrentOcelId';
import type { OCELMetadata } from './oCELMetadata';
import type { UploadingOCELMetadata } from './uploadingOCELMetadata';

export interface GetOcelResponse {
  current_ocel_id: GetOcelResponseCurrentOcelId;
  ocels: OCELMetadata[];
  uploading_ocels: UploadingOCELMetadata[];
}
