/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type GraphNodeShape = typeof GraphNodeShape[keyof typeof GraphNodeShape];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GraphNodeShape = {
  circle: 'circle',
  triangle: 'triangle',
  rectangle: 'rectangle',
  diamond: 'diamond',
  hexagon: 'hexagon',
} as const;
