/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { GraphNode } from './graphNode';
import type { GraphEdge } from './graphEdge';

export interface Graph {
  type: 'graph';
  nodes: GraphNode[];
  edges: GraphEdge[];
}
