/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { GraphEdgeArrowsItem0 } from './graphEdgeArrowsItem0';
import type { GraphEdgeArrowsItem1 } from './graphEdgeArrowsItem1';
import type { GraphEdgeColor } from './graphEdgeColor';
import type { GraphEdgeLabel } from './graphEdgeLabel';

export interface GraphEdge {
  source: string;
  target: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  arrows: [GraphEdgeArrowsItem0, GraphEdgeArrowsItem1];
  color?: GraphEdgeColor;
  label?: GraphEdgeLabel;
}
