/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface IntegerAttribute {
  attribute: string;
  type: 'integer';
  min: number;
  max: number;
}
