/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type NominalAttributeType = typeof NominalAttributeType[keyof typeof NominalAttributeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NominalAttributeType = {
  nominal: 'nominal',
} as const;
