/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { NominalAttributeSampleValuesItem } from './nominalAttributeSampleValuesItem';

export interface NominalAttribute {
  attribute: string;
  type: 'nominal';
  sample_values: NominalAttributeSampleValuesItem[];
  num_unique: number;
}
