/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { NumberInputMin } from './numberInputMin';
import type { NumberInputMax } from './numberInputMax';

export interface NumberInput {
  name: string;
  description?: string;
  default?: unknown;
  type: 'number';
  min?: NumberInputMin;
  max?: NumberInputMax;
}
