/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type NumericalAttributeType = typeof NumericalAttributeType[keyof typeof NumericalAttributeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NumericalAttributeType = {
  numerical: 'numerical',
} as const;
