/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type O2OCountFilterConfigDirection = typeof O2OCountFilterConfigDirection[keyof typeof O2OCountFilterConfigDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const O2OCountFilterConfigDirection = {
  source: 'source',
  target: 'target',
} as const;
