/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectCentricDirectlyFollowsGraphAnnotation } from './objectCentricDirectlyFollowsGraphAnnotation';
import type { Edge } from './edge';
import type { ObjectActivityEdge } from './objectActivityEdge';

export interface ObjectCentricDirectlyFollowsGraph {
  annotation: ObjectCentricDirectlyFollowsGraphAnnotation;
  object_types: string[];
  activities: string[];
  edges: Edge[];
  start_activities: ObjectActivityEdge[];
  end_activities: ObjectActivityEdge[];
  type: 'ocdfg';
}
