/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectAttributeFilterConfigMode } from './objectAttributeFilterConfigMode';
import type { ObjectAttributeFilterConfigMin } from './objectAttributeFilterConfigMin';
import type { ObjectAttributeFilterConfigMax } from './objectAttributeFilterConfigMax';
import type { ObjectAttributeFilterConfigValues } from './objectAttributeFilterConfigValues';
import type { ObjectAttributeFilterConfigRegex } from './objectAttributeFilterConfigRegex';

export interface ObjectAttributeFilterConfig {
  mode?: ObjectAttributeFilterConfigMode;
  type: 'object_attribute';
  target_type: string;
  attribute: string;
  min?: ObjectAttributeFilterConfigMin;
  max?: ObjectAttributeFilterConfigMax;
  values?: ObjectAttributeFilterConfigValues;
  regex?: ObjectAttributeFilterConfigRegex;
}
