/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ObjectAttributeFilterConfigEntityType = typeof ObjectAttributeFilterConfigEntityType[keyof typeof ObjectAttributeFilterConfigEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectAttributeFilterConfigEntityType = {
  event: 'event',
  object: 'object',
} as const;
