/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectTypeFilterConfigMode } from './objectTypeFilterConfigMode';

export interface ObjectTypeFilterConfig {
  mode?: ObjectTypeFilterConfigMode;
  type: 'object_type';
  object_types: string[];
}
