/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectActivityEdgeAnnotation } from './objectActivityEdgeAnnotation';

export interface ObjectActivityEdge {
  annotation: ObjectActivityEdgeAnnotation;
  object_type: string;
  activity: string;
}
