/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ObjectTypeFilterConfigType = typeof ObjectTypeFilterConfigType[keyof typeof ObjectTypeFilterConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectTypeFilterConfigType = {
  object_type: 'object_type',
} as const;
