/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectAttributeFilterConfigTimeRange } from './objectAttributeFilterConfigTimeRange';
import type { ObjectAttributeFilterConfigNumberRange } from './objectAttributeFilterConfigNumberRange';
import type { ObjectAttributeFilterConfigValues } from './objectAttributeFilterConfigValues';
import type { ObjectAttributeFilterConfigRegex } from './objectAttributeFilterConfigRegex';
import type { ObjectAttributeFilterConfigMode } from './objectAttributeFilterConfigMode';

export interface ObjectAttributeFilterConfig {
  target_type: string;
  attribute: string;
  time_range?: ObjectAttributeFilterConfigTimeRange;
  number_range?: ObjectAttributeFilterConfigNumberRange;
  values?: ObjectAttributeFilterConfigValues;
  regex?: ObjectAttributeFilterConfigRegex;
  mode?: ObjectAttributeFilterConfigMode;
  type: 'object_attribute';
}
