/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DfgEdge } from './dfgEdge';
import type { OcdfgStartActivities } from './ocdfgStartActivities';
import type { OcdfgEndActivities } from './ocdfgEndActivities';

export interface Ocdfg {
  object_types: string[];
  activities: string[];
  edges: DfgEdge[];
  start_activities: OcdfgStartActivities;
  end_activities: OcdfgEndActivities;
}
