/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { Transition } from './transition';
import type { Arc } from './arc';

export interface OCNet {
  places: string[];
  transitions: Transition[];
  arcs: Arc[];
}
