/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OCNet } from './oCNet';

export type OCNetModelObjects = {[key: string]: OCNet};
