/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { Graph } from './graph';
import type { CytoscapeGraph } from './cytoscapeGraph';

export type Output200 = Graph | CytoscapeGraph;
