/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcelEntity } from './ocelEntity';

export interface PaginatedResponse {
  page: number;
  page_size: number;
  total_pages: number;
  total_items: number;
  items: OcelEntity[];
}
