/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type PaginatedObjectsParams = {
/**
 * Object type name
 */
object_type: string;
page?: number;
page_size?: number;
sort_by?: string | null;
ascending?: boolean;
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
