/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginMetadataDescription } from './pluginMetadataDescription';

export interface PluginMetadata {
  name: string;
  label: string;
  version: string;
  description: PluginMetadataDescription;
}
