/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginMetadata } from './pluginMetadata';
import type { PluginDescriptionMethods } from './pluginDescriptionMethods';

export interface PluginDescription {
  metadata: PluginMetadata;
  methods: PluginDescriptionMethods;
}
