/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginMethod } from './pluginMethod';

export type PluginDescriptionMethods = {[key: string]: PluginMethod};
