/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginOCELLabel } from './pluginOCELLabel';
import type { PluginOCELDescription } from './pluginOCELDescription';

export interface PluginOCEL {
  name: string;
  label: PluginOCELLabel;
  description: PluginOCELDescription;
}
