/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginMethodDescription } from './pluginMethodDescription';
import type { PluginMethodTags } from './pluginMethodTags';
import type { PluginMethodInputModel } from './pluginMethodInputModel';
import type { PluginOCEL } from './pluginOCEL';

export interface PluginMethod {
  name: string;
  label: string;
  description?: PluginMethodDescription;
  tags?: PluginMethodTags;
  input_model?: PluginMethodInputModel;
  input_ocels: PluginOCEL[];
}
