/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { NumberInput } from './numberInput';
import type { EnumInput } from './enumInput';
import type { RInupt } from './rInupt';
import type { OcelInput } from './ocelInput';

export type PluginSummaryInputTypesItem = NumberInput | EnumInput | RInupt | OcelInput;
