/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { PluginSummaryInputTypesItem } from './pluginSummaryInputTypesItem';
import type { OutputDefinition } from './outputDefinition';

export interface PluginSummary {
  id: string;
  plugin: string;
  method: string;
  input_types: PluginSummaryInputTypesItem[];
  output_types: OutputDefinition;
}
