/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ResourceMetaData } from './resourceMetaData';
import type { ResourceResource } from './resourceResource';

export interface Resource {
  id: string;
  name: string;
  created_at: string;
  source: string;
  meta_data: ResourceMetaData;
  resource: ResourceResource;
}
