/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ResourceOutputMetaData } from './resourceOutputMetaData';
import type { ResourceOutputEntity } from './resourceOutputEntity';

export interface ResourceOutput {
  id: string;
  name: string;
  created_at: string;
  source: string;
  meta_data: ResourceOutputMetaData;
  entity: ResourceOutputEntity;
}
