/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface RInupt {
  name: string;
  description?: string;
  default?: unknown;
  type: 'resource';
  resource_types: string[];
}
