/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskResponsePercentage } from './taskResponsePercentage';
import type { TaskResponseMsg } from './taskResponseMsg';
import type { TaskResponseResult } from './taskResponseResult';

export interface TaskResponse {
  id: string;
  route: string;
  taskState: TaskState;
  percentage?: TaskResponsePercentage;
  msg?: TaskResponseMsg;
  result?: TaskResponseResult;
}
