/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskResponseOCDFGTaskId } from './taskResponseOCDFGTaskId';
import type { TaskResponseOCDFGResult } from './taskResponseOCDFGResult';
import type { TaskResponseOCDFGError } from './taskResponseOCDFGError';

export interface TaskResponseOCDFG {
  status: TaskState;
  taskId?: TaskResponseOCDFGTaskId;
  result?: TaskResponseOCDFGResult;
  error?: TaskResponseOCDFGError;
}
