/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskSummaryResult } from './taskSummaryResult';
import type { TaskSummaryMetadata } from './taskSummaryMetadata';

export interface TaskSummary {
  key: string;
  name: string;
  state: TaskState;
  result: TaskSummaryResult;
  metadata: TaskSummaryMetadata;
}
