/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskResult } from './taskResult';

export type TaskSummaryResult = TaskResult | null;
