/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskResponseTotemTaskId } from './taskResponseTotemTaskId';
import type { TaskResponseTotemResult } from './taskResponseTotemResult';
import type { TaskResponseTotemError } from './taskResponseTotemError';

export interface TaskResponseTotem {
  status: TaskState;
  taskId?: TaskResponseTotemTaskId;
  result?: TaskResponseTotemResult;
  error?: TaskResponseTotemError;
}
