/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskState } from './taskState';
import type { TaskResponseObjectCentricDirectlyFollowsGraphTaskId } from './taskResponseObjectCentricDirectlyFollowsGraphTaskId';
import type { TaskResponseObjectCentricDirectlyFollowsGraphResult } from './taskResponseObjectCentricDirectlyFollowsGraphResult';
import type { TaskResponseObjectCentricDirectlyFollowsGraphError } from './taskResponseObjectCentricDirectlyFollowsGraphError';

export interface TaskResponseObjectCentricDirectlyFollowsGraph {
  status: TaskState;
  taskId?: TaskResponseObjectCentricDirectlyFollowsGraphTaskId;
  result?: TaskResponseObjectCentricDirectlyFollowsGraphResult;
  error?: TaskResponseObjectCentricDirectlyFollowsGraphError;
}
