/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TimeFrameFilterConfigMode } from './timeFrameFilterConfigMode';
import type { TimeFrameFilterConfigTimeRangeItem0 } from './timeFrameFilterConfigTimeRangeItem0';
import type { TimeFrameFilterConfigTimeRangeItem1 } from './timeFrameFilterConfigTimeRangeItem1';

export interface TimeFrameFilterConfig {
  mode?: TimeFrameFilterConfigMode;
  type: 'time_frame';
  /**
   * @minItems 2
   * @maxItems 2
   */
  time_range: [TimeFrameFilterConfigTimeRangeItem0, TimeFrameFilterConfigTimeRangeItem1];
}
