/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TimeFrameFilterConfigType = typeof TimeFrameFilterConfigType[keyof typeof TimeFrameFilterConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeFrameFilterConfigType = {
  time_frame: 'time_frame',
} as const;
