/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TotemEdgeEc = typeof TotemEdgeEc[keyof typeof TotemEdgeEc];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TotemEdgeEc = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  '01': '0...1',
  '1*': '1..*',
  '0*': '0...*',
} as const;
