/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface TotemRelation {
  source: string;
  target: string;
  lc: string;
  lc_inverse: string;
  ec: string;
  ec_inverse: string;
  tr: string;
  tr_inverse: string;
}
