/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TotemEdgeAnnotation } from './totemEdgeAnnotation';
import type { TotemEdgeLc } from './totemEdgeLc';
import type { TotemEdgeLcInverse } from './totemEdgeLcInverse';
import type { TotemEdgeEc } from './totemEdgeEc';
import type { TotemEdgeEcInverse } from './totemEdgeEcInverse';
import type { TotemEdgeTr } from './totemEdgeTr';
import type { TotemEdgeTrInverse } from './totemEdgeTrInverse';

export interface TotemEdge {
  annotation: TotemEdgeAnnotation;
  source: string;
  target: string;
  lc: TotemEdgeLc;
  lc_inverse: TotemEdgeLcInverse;
  ec: TotemEdgeEc;
  ec_inverse: TotemEdgeEcInverse;
  tr: TotemEdgeTr;
  tr_inverse: TotemEdgeTrInverse;
}
