/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TotemEdgeTrInverse = typeof TotemEdgeTrInverse[keyof typeof TotemEdgeTrInverse];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TotemEdgeTrInverse = {
  D: 'D',
  Di: 'Di',
  I: 'I',
  Ii: 'Ii',
  P: 'P',
} as const;
