/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { AppStateObjectTypeColors } from './appStateObjectTypeColors';
import type { AppStateObjectTypeClasses } from './appStateObjectTypeClasses';

export interface AppState {
  objectTypeColors?: AppStateObjectTypeColors;
  objectTypeClasses?: AppStateObjectTypeClasses;
}
