/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DirectedGraphResponseMsg } from './directedGraphResponseMsg';
import type { DirectedGraphResponseAppState } from './directedGraphResponseAppState';
import type { DirectedGraphResponseGraph } from './directedGraphResponseGraph';

export interface DirectedGraphResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: DirectedGraphResponseMsg;
  appState?: DirectedGraphResponseAppState;
  graph: DirectedGraphResponseGraph;
}
