/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { DownloadOcelDownloadGetEmissions } from './downloadOcelDownloadGetEmissions';

export type DownloadOcelDownloadGetParams = {
/**
 * Controls on what level emission values are included in the resulting OCEL file as a new attribute. To preserve overall emissions, it is not possible to include both event and object emissions.
 */
emissions?: DownloadOcelDownloadGetEmissions;
};
