/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type DownloadOcelDownloadGetEmissions = typeof DownloadOcelDownloadGetEmissions[keyof typeof DownloadOcelDownloadGetEmissions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DownloadOcelDownloadGetEmissions = {
  events: 'events',
  objects: 'objects',
  false: false,
} as const;
