/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ImportDefaultParams = {
/**
 * Default OCEL key
 */
key: string;
/**
 * Dataset version (optional)
 */
version?: string | null;
};
