/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ImportOcelImportPostParams = {
/**
 * The name of the uploaded file
 */
name: string;
};
