/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcelResponseMsg } from './ocelResponseMsg';
import type { OcelResponseAppState } from './ocelResponseAppState';
import type { OcelData } from './ocelData';

export interface OcelResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: OcelResponseMsg;
  appState?: OcelResponseAppState;
  ocel: OcelData;
}
