/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcelDataMeta } from './ocelDataMeta';
import type { OcelDataActivityCounts } from './ocelDataActivityCounts';
import type { OcelDataObjectTypeCounts } from './ocelDataObjectTypeCounts';
import type { OcelDataMedianNumEventsPerObjectType } from './ocelDataMedianNumEventsPerObjectType';
import type { OcelDataE2oCounts } from './ocelDataE2oCounts';
import type { OcelDataE2oQualifierCounts } from './ocelDataE2oQualifierCounts';
import type { OcelDataAttributesItem } from './ocelDataAttributesItem';

export interface OcelData {
  meta: OcelDataMeta;
  numEvents: number;
  numObjects: number;
  activities: string[];
  activityCounts: OcelDataActivityCounts;
  objectTypes: string[];
  objectTypeCounts: OcelDataObjectTypeCounts;
  medianNumEventsPerObjectType: OcelDataMedianNumEventsPerObjectType;
  e2oCounts: OcelDataE2oCounts;
  e2oQualifierCounts: OcelDataE2oQualifierCounts;
  attributes: OcelDataAttributesItem[];
}
