/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcpnDotString } from './ocpnDotString';
import type { OcpnStructure } from './ocpnStructure';

export interface Ocpn {
  objectTypes: string[];
  dotString: OcpnDotString;
  structure: OcpnStructure;
}
