/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcpnResponseMsg } from './ocpnResponseMsg';
import type { OcpnResponseAppState } from './ocpnResponseAppState';
import type { Ocpn } from './ocpn';

export interface OcpnResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: OcpnResponseMsg;
  appState?: OcpnResponseAppState;
  ocpn: Ocpn;
}
