/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { OcpnStructureActivityTransitions } from './ocpnStructureActivityTransitions';
import type { OcpnStructureSourcePlaces } from './ocpnStructureSourcePlaces';
import type { OcpnStructureTargetPlaces } from './ocpnStructureTargetPlaces';
import type { OcpnStructureSilentTransitions } from './ocpnStructureSilentTransitions';
import type { OcpnStructurePlaces } from './ocpnStructurePlaces';
import type { Arc } from './arc';

export interface OcpnStructure {
  activityTransitions: OcpnStructureActivityTransitions;
  sourcePlaces: OcpnStructureSourcePlaces;
  targetPlaces: OcpnStructureTargetPlaces;
  silentTransitions: OcpnStructureSilentTransitions;
  places: OcpnStructurePlaces;
  arcs: Arc[];
}
