/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TaskStatusResponseMsg } from './taskStatusResponseMsg';
import type { TaskStatusResponseAppState } from './taskStatusResponseAppState';
import type { TaskResponse } from './taskResponse';

export interface TaskStatusResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: TaskStatusResponseMsg;
  appState?: TaskStatusResponseAppState;
  task: TaskResponse;
}
