/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type TaskState = typeof TaskState[keyof typeof TaskState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskState = {
  PENDING: 'PENDING',
  STARTED: 'STARTED',
  PROGRESS: 'PROGRESS',
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  RETRY: 'RETRY',
} as const;
