/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { WeightedDirectedGraphResponseMsg } from './weightedDirectedGraphResponseMsg';
import type { WeightedDirectedGraphResponseAppState } from './weightedDirectedGraphResponseAppState';
import type { WeightedDirectedGraphResponseGraph } from './weightedDirectedGraphResponseGraph';

export interface WeightedDirectedGraphResponse {
  session: string;
  route: string;
  state: string;
  status?: number;
  msg?: WeightedDirectedGraphResponseMsg;
  appState?: WeightedDirectedGraphResponseAppState;
  graph: WeightedDirectedGraphResponseGraph;
}
