/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyImportOcel,
  DefaultOCEL,
  DownloadOcelDownloadGetParams,
  GetDefaultOcelParams,
  HTTPValidationError,
  ImportDefaultOcelParams,
  ImportOcelParams
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Import OCEL 2.0 from .sqlite file
 */
export const getImportOcelUrl = (params: ImportOcelParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/import?${stringifiedParams}` : `http://localhost:8000/import`
}

export const importOcel = async (bodyImportOcel: BodyImportOcel,
    params: ImportOcelParams, options?: RequestInit): Promise<unknown> => {
    const formData = new FormData();
formData.append(`file`, bodyImportOcel.file)

  return customFetch<unknown>(getImportOcelUrl(params),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getImportOcelMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importOcel>>, TError,{data: BodyImportOcel;params: ImportOcelParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof importOcel>>, TError,{data: BodyImportOcel;params: ImportOcelParams}, TContext> => {

const mutationKey = ['importOcel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importOcel>>, {data: BodyImportOcel;params: ImportOcelParams}> = (props) => {
          const {data,params} = props ?? {};

          return  importOcel(data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportOcelMutationResult = NonNullable<Awaited<ReturnType<typeof importOcel>>>
    export type ImportOcelMutationBody = BodyImportOcel
    export type ImportOcelMutationError = HTTPValidationError

    /**
 * @summary Import OCEL 2.0 from .sqlite file
 */
export const useImportOcel = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importOcel>>, TError,{data: BodyImportOcel;params: ImportOcelParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importOcel>>,
        TError,
        {data: BodyImportOcel;params: ImportOcelParams},
        TContext
      > => {

      const mutationOptions = getImportOcelMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get default OCEL metadata
 */
export const getGetDefaultOcelUrl = (params?: GetDefaultOcelParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/ocel/default?${stringifiedParams}` : `http://localhost:8000/ocel/default`
}

export const getDefaultOcel = async (params?: GetDefaultOcelParams, options?: RequestInit): Promise<DefaultOCEL[]> => {
  
  return customFetch<DefaultOCEL[]>(getGetDefaultOcelUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetDefaultOcelQueryKey = (params?: GetDefaultOcelParams,) => {
    return [`http://localhost:8000/ocel/default`, ...(params ? [params]: [])] as const;
    }

    
export const getGetDefaultOcelQueryOptions = <TData = Awaited<ReturnType<typeof getDefaultOcel>>, TError = HTTPValidationError>(params?: GetDefaultOcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDefaultOcelQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDefaultOcel>>> = ({ signal }) => getDefaultOcel(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDefaultOcelQueryResult = NonNullable<Awaited<ReturnType<typeof getDefaultOcel>>>
export type GetDefaultOcelQueryError = HTTPValidationError


export function useGetDefaultOcel<TData = Awaited<ReturnType<typeof getDefaultOcel>>, TError = HTTPValidationError>(
 params: undefined |  GetDefaultOcelParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDefaultOcel>>,
          TError,
          Awaited<ReturnType<typeof getDefaultOcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDefaultOcel<TData = Awaited<ReturnType<typeof getDefaultOcel>>, TError = HTTPValidationError>(
 params?: GetDefaultOcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDefaultOcel>>,
          TError,
          Awaited<ReturnType<typeof getDefaultOcel>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDefaultOcel<TData = Awaited<ReturnType<typeof getDefaultOcel>>, TError = HTTPValidationError>(
 params?: GetDefaultOcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get default OCEL metadata
 */

export function useGetDefaultOcel<TData = Awaited<ReturnType<typeof getDefaultOcel>>, TError = HTTPValidationError>(
 params?: GetDefaultOcelParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDefaultOcel>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDefaultOcelQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Import default OCEL
 */
export const getImportDefaultOcelUrl = (params: ImportDefaultOcelParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/import-default?${stringifiedParams}` : `http://localhost:8000/import-default`
}

export const importDefaultOcel = async (params: ImportDefaultOcelParams, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getImportDefaultOcelUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getImportDefaultOcelMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importDefaultOcel>>, TError,{params: ImportDefaultOcelParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof importDefaultOcel>>, TError,{params: ImportDefaultOcelParams}, TContext> => {

const mutationKey = ['importDefaultOcel'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importDefaultOcel>>, {params: ImportDefaultOcelParams}> = (props) => {
          const {params} = props ?? {};

          return  importDefaultOcel(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImportDefaultOcelMutationResult = NonNullable<Awaited<ReturnType<typeof importDefaultOcel>>>
    
    export type ImportDefaultOcelMutationError = HTTPValidationError

    /**
 * @summary Import default OCEL
 */
export const useImportDefaultOcel = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importDefaultOcel>>, TError,{params: ImportDefaultOcelParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importDefaultOcel>>,
        TError,
        {params: ImportDefaultOcelParams},
        TContext
      > => {

      const mutationOptions = getImportDefaultOcelMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Download OCEL including app state
 */
export const getDownloadOcelDownloadGetUrl = (params: DownloadOcelDownloadGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/download?${stringifiedParams}` : `http://localhost:8000/download`
}

export const downloadOcelDownloadGet = async (params: DownloadOcelDownloadGetParams, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDownloadOcelDownloadGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getDownloadOcelDownloadGetQueryKey = (params: DownloadOcelDownloadGetParams,) => {
    return [`http://localhost:8000/download`, ...(params ? [params]: [])] as const;
    }

    
export const getDownloadOcelDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError = HTTPValidationError>(params: DownloadOcelDownloadGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadOcelDownloadGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadOcelDownloadGet>>> = ({ signal }) => downloadOcelDownloadGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadOcelDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadOcelDownloadGet>>>
export type DownloadOcelDownloadGetQueryError = HTTPValidationError


export function useDownloadOcelDownloadGet<TData = Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError = HTTPValidationError>(
 params: DownloadOcelDownloadGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOcelDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOcelDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOcelDownloadGet<TData = Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError = HTTPValidationError>(
 params: DownloadOcelDownloadGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOcelDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOcelDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOcelDownloadGet<TData = Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError = HTTPValidationError>(
 params: DownloadOcelDownloadGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download OCEL including app state
 */

export function useDownloadOcelDownloadGet<TData = Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError = HTTPValidationError>(
 params: DownloadOcelDownloadGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOcelDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadOcelDownloadGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



